//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerWindowsClient.Service_References.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMessenger")]
    public interface IMessenger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/GetEncryptedSessionKey", ReplyAction="http://tempuri.org/IMessenger/GetEncryptedSessionKeyResponse")]
        byte[] GetEncryptedSessionKey(byte[] exponent, byte[] modulus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/GetEncryptedSessionKey", ReplyAction="http://tempuri.org/IMessenger/GetEncryptedSessionKeyResponse")]
        System.Threading.Tasks.Task<byte[]> GetEncryptedSessionKeyAsync(byte[] exponent, byte[] modulus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/RegisterUser", ReplyAction="http://tempuri.org/IMessenger/RegisterUserResponse")]
        bool RegisterUser(string name, string username, string password, string email, byte[] iv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/RegisterUser", ReplyAction="http://tempuri.org/IMessenger/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string username, string password, string email, byte[] iv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/FriendUser", ReplyAction="http://tempuri.org/IMessenger/FriendUserResponse")]
        bool FriendUser(int idFirst, int idSecond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/FriendUser", ReplyAction="http://tempuri.org/IMessenger/FriendUserResponse")]
        System.Threading.Tasks.Task<bool> FriendUserAsync(int idFirst, int idSecond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/IsUniqueUsername", ReplyAction="http://tempuri.org/IMessenger/IsUniqueUsernameResponse")]
        bool IsUniqueUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/IsUniqueUsername", ReplyAction="http://tempuri.org/IMessenger/IsUniqueUsernameResponse")]
        System.Threading.Tasks.Task<bool> IsUniqueUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Login", ReplyAction="http://tempuri.org/IMessenger/LoginResponse")]
        bool Login(string username, string password, byte[] iv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Login", ReplyAction="http://tempuri.org/IMessenger/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password, byte[] iv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessengerChannel : IMessenger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerClient : System.ServiceModel.ClientBase<IMessenger>, IMessenger {
        
        public MessengerClient() {
        }
        
        public MessengerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessengerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetEncryptedSessionKey(byte[] exponent, byte[] modulus) {
            return base.Channel.GetEncryptedSessionKey(exponent, modulus);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetEncryptedSessionKeyAsync(byte[] exponent, byte[] modulus) {
            return base.Channel.GetEncryptedSessionKeyAsync(exponent, modulus);
        }
        
        public bool RegisterUser(string name, string username, string password, string email, byte[] iv) {
            return base.Channel.RegisterUser(name, username, password, email, iv);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string username, string password, string email, byte[] iv) {
            return base.Channel.RegisterUserAsync(name, username, password, email, iv);
        }
        
        public bool FriendUser(int idFirst, int idSecond) {
            return base.Channel.FriendUser(idFirst, idSecond);
        }
        
        public System.Threading.Tasks.Task<bool> FriendUserAsync(int idFirst, int idSecond) {
            return base.Channel.FriendUserAsync(idFirst, idSecond);
        }
        
        public bool IsUniqueUsername(string username) {
            return base.Channel.IsUniqueUsername(username);
        }
        
        public System.Threading.Tasks.Task<bool> IsUniqueUsernameAsync(string username) {
            return base.Channel.IsUniqueUsernameAsync(username);
        }
        
        public bool Login(string username, string password, byte[] iv) {
            return base.Channel.Login(username, password, iv);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password, byte[] iv) {
            return base.Channel.LoginAsync(username, password, iv);
        }
    }
}
